"""added create_at field to associations table

Revision ID: 0427ca5c1d85
Revises: 93e69c58b4ef
Create Date: 2026-01-18 15:39:54.221467

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0427ca5c1d85"
down_revision: Union[str, None] = "93e69c58b4ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first to avoid error with existing rows
    op.add_column(
        "admin_user_tracking",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Set current time for existing rows
    op.execute("UPDATE admin_user_tracking SET created_at = NOW()")

    # Now set nullable=False
    op.alter_column("admin_user_tracking", "created_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_user_tracking", "created_at")
    # ### end Alembic commands ###
