"""add punishment table and pahushment_ladder

Revision ID: 054e73c1daab
Revises: 775597843782
Create Date: 2025-09-24 04:00:18.682568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054e73c1daab'
down_revision: Union[str, None] = '775597843782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punishment_ladder',
    sa.Column('chat_id', sa.String(length=32), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('punishment_type', sa.Enum('WARNING', 'MUTE', 'BAN', name='punishmenttype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punishment_ladder_chat_id'), 'punishment_ladder', ['chat_id'], unique=False)
    op.create_table('punishments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('punishment_type', sa.Enum('WARNING', 'MUTE', 'BAN', name='punishmenttype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('punished_by_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['punished_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punishments')
    op.drop_index(op.f('ix_punishment_ladder_chat_id'), table_name='punishment_ladder')
    op.drop_table('punishment_ladder')
    # ### end Alembic commands ###
