"""added foreign key for archive chat

Revision ID: 0a2d13d2b807
Revises: efc575a1cbb5
Create Date: 2025-11-24 17:26:01.023282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2d13d2b807'
down_revision: Union[str, None] = 'efc575a1cbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_sessions', 'chat_sessions', ['archive_chat_id'], ['chat_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    # ### end Alembic commands ###
