"""added foreign key for archive chat

Revision ID: 0a2d13d2b807
Revises: efc575a1cbb5
Create Date: 2025-11-24 17:26:01.023282

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a2d13d2b807"
down_revision: Union[str, None] = "efc575a1cbb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Очистить некорректные ссылки перед созданием FK
    op.execute("""
        UPDATE chat_sessions 
        SET archive_chat_id = NULL 
        WHERE archive_chat_id IS NOT NULL 
        AND archive_chat_id NOT IN (SELECT chat_id FROM chat_sessions)
    """)

    # Теперь можно безопасно создать FK
    op.create_foreign_key(
        None,
        "chat_sessions",
        "chat_sessions",
        ["archive_chat_id"],
        ["chat_id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_sessions", type_="foreignkey")
    # ### end Alembic commands ###
