"""rename fields durations_minutes to duration_seconds

Revision ID: 0efefc61e5dd
Revises: f94ca6c6b978
Create Date: 2025-09-29 19:35:51.034753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efefc61e5dd'
down_revision: Union[str, None] = 'f94ca6c6b978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punishment_ladder', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.drop_column('punishment_ladder', 'duration_minutes')
    op.add_column('punishments', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.drop_column('punishments', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punishments', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('punishments', 'duration_seconds')
    op.add_column('punishment_ladder', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('punishment_ladder', 'duration_seconds')
    # ### end Alembic commands ###
