"""Initial migration

Revision ID: 145c66227eb6
Revises: 
Create Date: 2025-05-09 12:57:15.893656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145c66227eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_tg_id', 'users', ['tg_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_chat', 'chat_messages', ['chat_id'], unique=False)
    op.create_index('idx_message_created', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_message_user', 'chat_messages', ['user_id'], unique=False)
    op.create_table('message_replies',
    sa.Column('original_message_id', sa.Integer(), nullable=False),
    sa.Column('reply_message_id', sa.Integer(), nullable=False),
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.Column('reply_user_id', sa.Integer(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['original_user_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['reply_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['reply_user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reply_original_message', 'message_replies', ['original_message_id'], unique=False)
    op.create_index('idx_reply_time', 'message_replies', ['created_at'], unique=False)
    op.create_index('idx_reply_users', 'message_replies', ['original_user_id', 'reply_user_id'], unique=False)
    op.create_table('moderator_activity',
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=False),
    sa.Column('next_message_id', sa.Integer(), nullable=False),
    sa.Column('inactive_period_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['next_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_moderator', 'moderator_activity', ['moderator_id'], unique=False)
    op.create_index('idx_activity_period', 'moderator_activity', ['inactive_period_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_period', table_name='moderator_activity')
    op.drop_index('idx_activity_moderator', table_name='moderator_activity')
    op.drop_table('moderator_activity')
    op.drop_index('idx_reply_users', table_name='message_replies')
    op.drop_index('idx_reply_time', table_name='message_replies')
    op.drop_index('idx_reply_original_message', table_name='message_replies')
    op.drop_table('message_replies')
    op.drop_index('idx_message_user', table_name='chat_messages')
    op.drop_index('idx_message_created', table_name='chat_messages')
    op.drop_index('idx_message_chat', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_user_tg_id', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_table('users')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
