"""Update Integer to String

Revision ID: 2bfc3195ad2a
Revises: 5279eb82cfac
Create Date: 2025-05-09 13:30:46.726028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfc3195ad2a'
down_revision: Union[str, None] = '5279eb82cfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_activity', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'moderator_activity', 'chat_sessions', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderator_activity', type_='foreignkey')
    op.drop_column('moderator_activity', 'chat_id')
    # ### end Alembic commands ###
