"""add chat_id field to MessageTemplate table

Revision ID: 3ff537ba96c6
Revises: 78fe23337e3e
Create Date: 2025-07-11 19:40:00.324069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff537ba96c6'
down_revision: Union[str, None] = '78fe23337e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_templates', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('message_templates_title_key'), 'message_templates', type_='unique')
    op.create_index(op.f('ix_message_templates_chat_id'), 'message_templates', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_templates_title'), 'message_templates', ['title'], unique=False)
    op.create_foreign_key(None, 'message_templates', 'chat_sessions', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_templates', type_='foreignkey')
    op.drop_index(op.f('ix_message_templates_title'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_chat_id'), table_name='message_templates')
    op.create_unique_constraint(op.f('message_templates_title_key'), 'message_templates', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('message_templates', 'chat_id')
    # ### end Alembic commands ###
