"""add file_unique_id field to QuickReponseCategoryModel

Revision ID: 41be1b6d1d23
Revises: 6cd9260dabc3
Create Date: 2025-07-03 14:26:32.802731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41be1b6d1d23'
down_revision: Union[str, None] = '6cd9260dabc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_response_media', sa.Column('file_unique_id', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'quick_response_media', ['file_unique_id'])
    op.drop_column('quick_response_media', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_response_media', sa.Column('file_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quick_response_media', type_='unique')
    op.drop_column('quick_response_media', 'file_unique_id')
    # ### end Alembic commands ###
