"""Remove ModeratorActivity model

Revision ID: 50f08db74256
Revises: fa611af2cb0d
Create Date: 2025-09-30 00:45:17.398188

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50f08db74256"
down_revision: Union[str, None] = "fa611af2cb0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_activity_moderator"), table_name="moderator_activity")
    op.drop_index(op.f("idx_activity_period"), table_name="moderator_activity")
    op.drop_table("moderator_activity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ActivityRepository",
        sa.Column("last_message_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("next_message_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "inactive_period_seconds", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat_sessions.id"],
            name=op.f("moderator_activity_chat_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["last_message_id"],
            ["chat_messages.id"],
            name=op.f("moderator_activity_last_message_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["next_message_id"],
            ["chat_messages.id"],
            name=op.f("moderator_activity_next_message_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("moderator_activity_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("moderator_activity_pkey")),
    )
    op.create_index(
        op.f("idx_activity_period"),
        "moderator_activity",
        ["inactive_period_seconds"],
        unique=False,
    )
    op.create_index(
        op.f("idx_activity_moderator"), "moderator_activity", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
