"""Update Integer to String

Revision ID: 5279eb82cfac
Revises: 145c66227eb6
Create Date: 2025-05-09 13:11:35.649684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5279eb82cfac'
down_revision: Union[str, None] = '145c66227eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('chat_sessions', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_column('chat_sessions', 'name')
    op.drop_constraint('message_replies_original_user_id_fkey', 'message_replies', type_='foreignkey')
    op.drop_constraint('message_replies_reply_user_id_fkey', 'message_replies', type_='foreignkey')
    op.create_foreign_key(None, 'message_replies', 'users', ['reply_user_id'], ['id'])
    op.create_foreign_key(None, 'message_replies', 'users', ['original_user_id'], ['id'])
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'message_replies', type_='foreignkey')
    op.drop_constraint(None, 'message_replies', type_='foreignkey')
    op.create_foreign_key('message_replies_reply_user_id_fkey', 'message_replies', 'users', ['reply_user_id'], ['tg_id'])
    op.create_foreign_key('message_replies_original_user_id_fkey', 'message_replies', 'users', ['original_user_id'], ['tg_id'])
    op.add_column('chat_sessions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('chat_sessions', 'chat_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('chat_sessions', 'title')
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
