"""remove filename field to QuickReponseCategoryModel

Revision ID: 5cf7ba318d44
Revises: 41be1b6d1d23
Create Date: 2025-07-03 14:28:35.661655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf7ba318d44'
down_revision: Union[str, None] = '41be1b6d1d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_response_media', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_response_media', sa.Column('filename', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
