"""Update Punishment model, change chat_id to FK

Revision ID: 6ad10f7e2837
Revises: 50f08db74256
Create Date: 2025-09-30 01:55:14.908146

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ad10f7e2837"
down_revision: Union[str, None] = "50f08db74256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "punishments",
        "chat_id",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="chat_id::integer",
    )
    op.create_foreign_key(
        "fk_punishments_chat_id",
        "punishments",
        "chat_sessions",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_punishments_chat_id", "punishments", type_="foreignkey")
    op.alter_column(
        "punishments",
        "chat_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        postgresql_using="chat_id::varchar",
    )
    # ### end Alembic commands ###
