"""add file_id field to QuickReponseCategoryModel

Revision ID: 6cd9260dabc3
Revises: 773cf7d4ffd7
Create Date: 2025-07-03 14:16:58.291418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd9260dabc3'
down_revision: Union[str, None] = '773cf7d4ffd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_response_media', sa.Column('file_id', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_response_media', 'file_id')
    # ### end Alembic commands ###
