"""add_admin_user_tracking_association_table

Revision ID: 775597843782
Revises: b84569cb61d6
Create Date: 2025-08-05 21:56:14.188878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775597843782'
down_revision: Union[str, None] = 'b84569cb61d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_tracking',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('tracked_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'tracked_user_id')
    )
    op.create_index('idx_message_chat_created', 'chat_messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_message_type', 'chat_messages', ['message_type'], unique=False)
    op.create_index('idx_message_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_message_user_type', 'chat_messages', ['user_id', 'message_type'], unique=False)
    op.create_index('idx_chat_session_chat_id', 'chat_sessions', ['chat_id'], unique=False)
    op.create_index('idx_chat_session_title', 'chat_sessions', ['title'], unique=False)
    op.create_index('idx_reaction_chat_created', 'message_reactions', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_reaction_user_created', 'message_reactions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_reply_chat', 'message_replies', ['chat_id'], unique=False)
    op.create_index('idx_reply_chat_created', 'message_replies', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_reply_response_time', 'message_replies', ['response_time_seconds'], unique=False)
    op.create_index('idx_reply_user', 'message_replies', ['reply_user_id'], unique=False)
    op.create_index('idx_reply_user_created', 'message_replies', ['reply_user_id', 'created_at'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_reply_user_created', table_name='message_replies')
    op.drop_index('idx_reply_user', table_name='message_replies')
    op.drop_index('idx_reply_response_time', table_name='message_replies')
    op.drop_index('idx_reply_chat_created', table_name='message_replies')
    op.drop_index('idx_reply_chat', table_name='message_replies')
    op.drop_index('idx_reaction_user_created', table_name='message_reactions')
    op.drop_index('idx_reaction_chat_created', table_name='message_reactions')
    op.drop_index('idx_chat_session_title', table_name='chat_sessions')
    op.drop_index('idx_chat_session_chat_id', table_name='chat_sessions')
    op.drop_index('idx_message_user_type', table_name='chat_messages')
    op.drop_index('idx_message_user_created', table_name='chat_messages')
    op.drop_index('idx_message_type', table_name='chat_messages')
    op.drop_index('idx_message_chat_created', table_name='chat_messages')
    op.drop_table('admin_user_tracking')
    # ### end Alembic commands ###
