"""fix

Revision ID: 78fe23337e3e
Revises: 96d0e522ab55
Create Date: 2025-07-06 15:39:20.907415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fe23337e3e'
down_revision: Union[str, None] = '96d0e522ab55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_media', sa.Column('template_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('template_media_response_id_fkey'), 'template_media', type_='foreignkey')
    op.create_foreign_key(None, 'template_media', 'message_templates', ['template_id'], ['id'])
    op.drop_column('template_media', 'response_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_media', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'template_media', type_='foreignkey')
    op.create_foreign_key(op.f('template_media_response_id_fkey'), 'template_media', 'message_templates', ['response_id'], ['id'])
    op.drop_column('template_media', 'template_id')
    # ### end Alembic commands ###
