"""added show_welcome_text to chat_settings table

Revision ID: 81102062da65
Revises: 4d7e54945139
Create Date: 2026-01-22 22:53:11.249760

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81102062da65"
down_revision: Union[str, None] = "4d7e54945139"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_settings",
        sa.Column(
            "show_welcome_text",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("chat_settings", "show_welcome_text", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_settings", "show_welcome_text")
    # ### end Alembic commands ###
