"""added admin action log table

Revision ID: 907d4d8c6977
Revises: 19df38c2c82d
Create Date: 2025-11-14 05:30:48.571362

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907d4d8c6977"
down_revision: Union[str, None] = "19df38c2c82d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Проверяем, существует ли таблица
    table_exists = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
            "WHERE table_name = 'admin_action_logs')"
        )
    ).scalar()

    if table_exists:
        # Таблица уже существует, проверяем и добавляем поле details, если его нет
        details_exists = conn.execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_name = 'admin_action_logs' AND column_name = 'details')"
            )
        ).scalar()

        if not details_exists:
            op.add_column(
                "admin_action_logs", sa.Column("details", sa.Text(), nullable=True)
            )

        # Проверяем и добавляем 'reply_message' в enum, если его нет
        enum_exists = conn.execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adminactiontype')"
            )
        ).scalar()

        if enum_exists:
            reply_message_exists = conn.execute(
                sa.text(
                    "SELECT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'reply_message' "
                    "AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'adminactiontype'))"
                )
            ).scalar()
            if not reply_message_exists:
                op.execute("ALTER TYPE adminactiontype ADD VALUE 'reply_message'")
    else:
        # Таблица не существует, создаем её
        # Проверяем, существует ли enum
        enum_exists = conn.execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adminactiontype')"
            )
        ).scalar()

        if not enum_exists:
            # Создаем enum, если его нет
            op.execute(
                "CREATE TYPE adminactiontype AS ENUM "
                "('report_user', 'report_chat', 'report_all_users', 'add_template', "
                "'delete_template', 'add_category', 'delete_category', 'send_message', "
                "'delete_message', 'reply_message')"
            )
        else:
            # Если enum существует, добавляем недостающие значения
            reply_message_exists = conn.execute(
                sa.text(
                    "SELECT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'reply_message' "
                    "AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'adminactiontype'))"
                )
            ).scalar()
            if not reply_message_exists:
                op.execute("ALTER TYPE adminactiontype ADD VALUE 'reply_message'")

        # Создаем таблицу через прямой SQL, чтобы избежать проблем с созданием enum
        op.execute(
            """
            CREATE TABLE admin_action_logs (
                id SERIAL PRIMARY KEY,
                admin_id INTEGER NOT NULL,
                action_type adminactiontype NOT NULL,
                details TEXT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                CONSTRAINT fk_admin_action_logs_admin_id 
                    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE
            )
            """
        )

        # Создаем индексы
        op.create_index(
            "idx_admin_action_log_admin",
            "admin_action_logs",
            ["admin_id"],
            unique=False,
        )
        op.create_index(
            "idx_admin_action_log_admin_created",
            "admin_action_logs",
            ["admin_id", "created_at"],
            unique=False,
        )
        op.create_index(
            "idx_admin_action_log_created",
            "admin_action_logs",
            ["created_at"],
            unique=False,
        )
        op.create_index(
            "idx_admin_action_log_type",
            "admin_action_logs",
            ["action_type"],
            unique=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_admin_action_log_type", table_name="admin_action_logs")
    op.drop_index("idx_admin_action_log_created", table_name="admin_action_logs")
    op.drop_index("idx_admin_action_log_admin_created", table_name="admin_action_logs")
    op.drop_index("idx_admin_action_log_admin", table_name="admin_action_logs")
    op.drop_table("admin_action_logs")
    # ### end Alembic commands ###
