"""Fix reply message model

Revision ID: 96aafa86c796
Revises: e65aa6503da5
Create Date: 2025-05-15 20:44:49.775391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96aafa86c796'
down_revision: Union[str, None] = 'e65aa6503da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_replies', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('message_replies', sa.Column('original_message_url', sa.String(), nullable=False))
    op.drop_index('idx_reply_original_message', table_name='message_replies')
    op.drop_index('idx_reply_users', table_name='message_replies')
    op.drop_constraint('message_replies_original_user_id_fkey', 'message_replies', type_='foreignkey')
    op.drop_constraint('message_replies_original_message_id_fkey', 'message_replies', type_='foreignkey')
    op.create_foreign_key(None, 'message_replies', 'chat_sessions', ['chat_id'], ['id'])
    op.drop_column('message_replies', 'original_user_id')
    op.drop_column('message_replies', 'original_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_replies', sa.Column('original_message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message_replies', sa.Column('original_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message_replies', type_='foreignkey')
    op.create_foreign_key('message_replies_original_message_id_fkey', 'message_replies', 'chat_messages', ['original_message_id'], ['id'])
    op.create_foreign_key('message_replies_original_user_id_fkey', 'message_replies', 'users', ['original_user_id'], ['id'])
    op.create_index('idx_reply_users', 'message_replies', ['original_user_id', 'reply_user_id'], unique=False)
    op.create_index('idx_reply_original_message', 'message_replies', ['original_message_id'], unique=False)
    op.drop_column('message_replies', 'original_message_url')
    op.drop_column('message_replies', 'chat_id')
    # ### end Alembic commands ###
