"""rename tables

Revision ID: 96d0e522ab55
Revises: fc22cd18037f
Create Date: 2025-07-06 15:28:14.309857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d0e522ab55'
down_revision: Union[str, None] = 'fc22cd18037f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_categories_name'), 'template_categories', ['name'], unique=True)
    op.create_table('message_templates',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['template_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_message_templates_author_id'), 'message_templates', ['author_id'], unique=False)
    op.create_index(op.f('ix_message_templates_category_id'), 'message_templates', ['category_id'], unique=False)
    op.create_table('template_media',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=256), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_unique_id')
    )
    op.drop_table('quick_response_media')
    op.drop_index(op.f('ix_quick_responses_author_id'), table_name='quick_responses')
    op.drop_index(op.f('ix_quick_responses_category_id'), table_name='quick_responses')
    op.drop_table('quick_responses')
    op.drop_index(op.f('ix_quick_response_categories_name'), table_name='quick_response_categories')
    op.drop_table('quick_response_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_response_categories',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quick_response_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='quick_response_categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_quick_response_categories_name'), 'quick_response_categories', ['name'], unique=True)
    op.create_table('quick_responses',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quick_responses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='quick_responses_author_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['quick_response_categories.id'], name='quick_responses_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quick_responses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_quick_responses_category_id'), 'quick_responses', ['category_id'], unique=False)
    op.create_index(op.f('ix_quick_responses_author_id'), 'quick_responses', ['author_id'], unique=False)
    op.create_table('quick_response_media',
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('file_unique_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['quick_responses.id'], name=op.f('quick_response_media_response_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quick_response_media_pkey')),
    sa.UniqueConstraint('file_unique_id', name=op.f('quick_response_media_file_unique_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('template_media')
    op.drop_index(op.f('ix_message_templates_category_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_author_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_template_categories_name'), table_name='template_categories')
    op.drop_table('template_categories')
    # ### end Alembic commands ###
