"""remove user_id colomn from report_schedules table

Revision ID: 981d540d991f
Revises: 88cd774ac729
Create Date: 2025-12-14 17:55:53.027799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981d540d991f'
down_revision: Union[str, None] = '88cd774ac729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_schedule_user_chat'), table_name='report_schedules')
    op.create_unique_constraint(None, 'report_schedules', ['chat_id'])
    op.drop_constraint(op.f('report_schedules_user_id_fkey'), 'report_schedules', type_='foreignkey')
    op.drop_column('report_schedules', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_schedules', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('report_schedules_user_id_fkey'), 'report_schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'report_schedules', type_='unique')
    op.create_index(op.f('idx_schedule_user_chat'), 'report_schedules', ['user_id', 'chat_id'], unique=True)
    # ### end Alembic commands ###
