"""add quick_responses

Revision ID: 9a051054fc74
Revises: f1362a28cec9
Create Date: 2025-06-24 23:11:57.018904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a051054fc74'
down_revision: Union[str, None] = 'f1362a28cec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_response_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_response_categories_name'), 'quick_response_categories', ['name'], unique=True)
    op.create_table('quick_responses',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['quick_response_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_responses_author_id'), 'quick_responses', ['author_id'], unique=False)
    op.create_index(op.f('ix_quick_responses_category_id'), 'quick_responses', ['category_id'], unique=False)
    op.drop_index('ix_admin_chat_access_admin_id', table_name='admin_chat_access')
    op.drop_index('ix_admin_chat_access_chat_id', table_name='admin_chat_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_admin_chat_access_chat_id', 'admin_chat_access', ['chat_id'], unique=False)
    op.create_index('ix_admin_chat_access_admin_id', 'admin_chat_access', ['admin_id'], unique=False)
    op.drop_index(op.f('ix_quick_responses_category_id'), table_name='quick_responses')
    op.drop_index(op.f('ix_quick_responses_author_id'), table_name='quick_responses')
    op.drop_table('quick_responses')
    op.drop_index(op.f('ix_quick_response_categories_name'), table_name='quick_response_categories')
    op.drop_table('quick_response_categories')
    # ### end Alembic commands ###
