"""add is_antibot_enabled to chat_sessions

Revision ID: b71d8e70842f
Revises: c08827b50173
Create Date: 2026-01-10 13:32:40.015415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71d8e70842f'
down_revision: Union[str, None] = 'c08827b50173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_antibot_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE chat_sessions SET is_antibot_enabled = FALSE")
    op.alter_column('chat_sessions', 'is_antibot_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_antibot_enabled')
    # ### end Alembic commands ###
