"""added message_reactions table

Revision ID: b84569cb61d6
Revises: 3ff537ba96c6
Create Date: 2025-08-01 17:37:03.917720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84569cb61d6'
down_revision: Union[str, None] = '3ff537ba96c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reactions',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('ADDED', 'REMOVED', 'CHANGED', name='reactionaction'), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('message_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reaction_chat_message', 'message_reactions', ['chat_id', 'message_id'], unique=False)
    op.create_index('idx_reaction_created_at', 'message_reactions', ['created_at'], unique=False)
    op.create_index('idx_reaction_user', 'message_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reaction_user', table_name='message_reactions')
    op.drop_index('idx_reaction_created_at', table_name='message_reactions')
    op.drop_index('idx_reaction_chat_message', table_name='message_reactions')
    op.drop_table('message_reactions')
    # ### end Alembic commands ###
