"""added admin action log table

Revision ID: c4e39a60309a
Revises: 19df38c2c82d
Create Date: 2025-11-14 06:11:21.029092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e39a60309a'
down_revision: Union[str, None] = '19df38c2c82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('REPORT_USER', 'REPORT_CHAT', 'REPORT_ALL_USERS', 'ADD_TEMPLATE', 'DELETE_TEMPLATE', 'ADD_CATEGORY', 'DELETE_CATEGORY', 'SEND_MESSAGE', 'DELETE_MESSAGE', 'REPLY_MESSAGE', name='adminactiontype'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_action_log_admin', 'admin_action_logs', ['admin_id'], unique=False)
    op.create_index('idx_admin_action_log_admin_created', 'admin_action_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_admin_action_log_created', 'admin_action_logs', ['created_at'], unique=False)
    op.create_index('idx_admin_action_log_type', 'admin_action_logs', ['action_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_admin_action_log_type', table_name='admin_action_logs')
    op.drop_index('idx_admin_action_log_created', table_name='admin_action_logs')
    op.drop_index('idx_admin_action_log_admin_created', table_name='admin_action_logs')
    op.drop_index('idx_admin_action_log_admin', table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
