"""rename moderator_id filed to user_id

Revision ID: e65aa6503da5
Revises: 0ea5c3604f36
Create Date: 2025-05-15 19:48:29.242982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65aa6503da5'
down_revision: Union[str, None] = '0ea5c3604f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_activity', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('idx_activity_moderator', table_name='moderator_activity')
    op.create_index('idx_activity_moderator', 'moderator_activity', ['user_id'], unique=False)
    op.drop_constraint('moderator_activity_moderator_id_fkey', 'moderator_activity', type_='foreignkey')
    op.create_foreign_key(None, 'moderator_activity', 'users', ['user_id'], ['id'])
    op.drop_column('moderator_activity', 'moderator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_activity', sa.Column('moderator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'moderator_activity', type_='foreignkey')
    op.create_foreign_key('moderator_activity_moderator_id_fkey', 'moderator_activity', 'users', ['moderator_id'], ['id'])
    op.drop_index('idx_activity_moderator', table_name='moderator_activity')
    op.create_index('idx_activity_moderator', 'moderator_activity', ['moderator_id'], unique=False)
    op.drop_column('moderator_activity', 'user_id')
    # ### end Alembic commands ###
