"""added release notes table

Revision ID: efc575a1cbb5
Revises: a1b2c3d4e5f6
Create Date: 2025-11-19 11:13:07.526863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc575a1cbb5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_notes',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('admin_action_logs', 'action_type',
               existing_type=postgresql.ENUM('report_user', 'report_chat', 'report_all_users', 'add_template', 'delete_template', 'add_category', 'delete_category', 'send_message', 'delete_message', 'reply_message', 'change_user_role', name='adminactiontype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_action_logs', 'action_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('report_user', 'report_chat', 'report_all_users', 'add_template', 'delete_template', 'add_category', 'delete_category', 'send_message', 'delete_message', 'reply_message', 'change_user_role', name='adminactiontype'),
               existing_nullable=False)
    op.drop_table('release_notes')
    # ### end Alembic commands ###
