"""add archive_chat_id to chat_session

Revision ID: f94ca6c6b978
Revises: 054e73c1daab
Create Date: 2025-09-29 01:05:05.988363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94ca6c6b978'
down_revision: Union[str, None] = '054e73c1daab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('archive_chat_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'archive_chat_id')
    # ### end Alembic commands ###
