"""make_start_end_tolerance_breaks_nullable

Revision ID: f9cad880a68f
Revises: 0427ca5c1d85
Create Date: 2026-01-21 16:50:16.397903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9cad880a68f'
down_revision: Union[str, None] = '0427ca5c1d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('breaks_time', sa.Integer(), nullable=True))
    op.alter_column('chat_settings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('chat_settings', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('chat_settings', 'tolerance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_settings', 'tolerance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_settings', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('chat_settings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('chat_settings', 'breaks_time')
    # ### end Alembic commands ###
