"""added user_chat_status table

Revision ID: fa611af2cb0d
Revises: 0efefc61e5dd
Create Date: 2025-09-30 00:10:55.670914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa611af2cb0d'
down_revision: Union[str, None] = '0efefc61e5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_chat_access_admin_chat', 'admin_chat_access', ['admin_id', 'chat_id'], unique=True)
    op.create_index('idx_punishment_chat_id', 'punishments', ['chat_id'], unique=False)
    op.create_index('idx_punishment_punished_by_id', 'punishments', ['punished_by_id'], unique=False)
    op.create_index('idx_punishment_type', 'punishments', ['punishment_type'], unique=False)
    op.create_index('idx_punishment_user_id', 'punishments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_punishment_user_id', table_name='punishments')
    op.drop_index('idx_punishment_type', table_name='punishments')
    op.drop_index('idx_punishment_punished_by_id', table_name='punishments')
    op.drop_index('idx_punishment_chat_id', table_name='punishments')
    op.drop_index('idx_admin_chat_access_admin_chat', table_name='admin_chat_access')
    op.drop_table('user_chat_status')
    # ### end Alembic commands ###
