"""add file_id field to QuickReponseCategoryModel

Revision ID: fc22cd18037f
Revises: 5cf7ba318d44
Create Date: 2025-07-03 14:41:04.121307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc22cd18037f'
down_revision: Union[str, None] = '5cf7ba318d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_response_media', sa.Column('file_id', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_response_media', 'file_id')
    # ### end Alembic commands ###
